ci:
  autoupdate_schedule: "quarterly"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: debug-statements
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.9.0
  hooks:
  - id: black
    files: ^openff
  - id: black-jupyter
    files: ^examples
- repo: https://github.com/PyCQA/isort
  rev: 6.1.0
  hooks:
  - id: isort
    files: ^openff
- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    files: ^openff
    additional_dependencies:
      - 'flake8-all-not-strings'
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.1
  hooks:
    - id: nbqa-isort
    - id: nbqa-flake8
      args:
        - '--select=F'
