version: 2

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build PDF in addition to default HTML and JSON
formats:
    - pdf

conda:
  environment: devtools/conda-envs/docs.yaml
