# .readthedocs.yml
version: 2
build:
  image: stable
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10

python:
  version: 3.7
  setup_py_install: true

# Build PDF in addition to default HTML and JSON
formats:
    - pdf

conda:
  file: docs/environment.yml
