name: lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install isort / black
        run: |
          pip install isort black

      - name: Run isort
        run: |
          isort --recursive --check-only openff

      - name: Run black
        run: |
          black openff --check
